### ISSUE TITLE
Update seems not to be working

### ISSUE THREAD

**Issue by tanvn** [palantir/bulldozer#111]
Hi,
I just started using your amazing app today, and the auto-merge function is working fine
but the `update branch` part seems not to be working.
Here is my PR : https://github.com/tanvn/fp-in-scala-with-ci/pull/26
I added a `wip` label to the PR as `wip` is on my whitelist for `update` in my config file.
https://github.com/tanvn/fp-in-scala-with-ci/blob/master/.bulldozer.yml

Thanks in advance.

**Comment by tanvn** [comment]
I am sorry, I just read the code and made some tests to got my PR updated !

**Comment by bluekeyes** [comment]
Glad you figured this out. Is there anything we could add to the documentation to make this easier?

**Comment by tanvn** [comment]
@bluekeyes actually I dived into the code and took a look at the logs and found out that I must add labels to my PR first then trigger some changes to my PR or the targeted branch to make the bot do the thing. I think if you guys could add a GIF to the document depicting an example of the flow like : 

1. Create a PR
2. Add a label to the PR
3. Make a change to the target branch
4. See the PR checking auto update or auto merge

then it could help users have a better understand of how the bot works. 
In fact I also read some pass issues and found out how things work.

Have a nice day !
