### ISSUE TITLE
Bug: Bulldozer does not always merge green PRs

### ISSUE THREAD

**Issue by ferozco** [palantir/bulldozer#115]
I've recently seen a large number of PRs opened by excavator remain open although they are green and have the `merge when ready` label applied. Toggling the label or interacting with the PR in any way seem to trigger the merge

**Comment by bluekeyes** [comment]
This appears to be due to our internal rate limiting configuration on GitHub and not a bug in Bulldozer. I've filed an internal ticket to investigate more.
