### ISSUE TITLE
Do not merge PRs with no required checks by default

### ISSUE THREAD

**Issue by bluekeyes** [palantir/bulldozer#122]
Currently, Bulldozer will wait for any required status checks defined in GitHub or in the configuration before attempting a merge, but it does not require that at least one of these checks exists. This means that Bulldozer will immediately merge pull requests on repositories that don't define any required checks, which can get exciting if branch protection is accidentally removed or modified.

By default, Bulldozer should refuse to merge pull requests in any repository that does not specify at least one required check via either branch protection or the configuration. Users who wish to keep the current behavior can set a new property, `allow_merge_with_no_checks`. This will probably be a per-repository configuration option rather than a server option.

**Comment by iamdanfox** [comment]
I think it's worth adding a special edge-case to change this behaviour. Bulldozer seems to be almost perfect (in that people never seem to ask for help in slack), but in this specific workflow I think bulldozer's behaviour is not what humans expect:

1. someone makes a `release/1.2.3` branch, branched off develop. (This contains a bulldozer.yml file)
1. they make some bugfix PR, targetting that release branch, and slap on a `merge when ready` and `autorelease` labels as it's a fairly urgent piece of work and they want it to go out as soon as it's code-reviewed
1. the PR _instantly_ merges, without waiting for CI or policy-bot

![image](https://user-images.githubusercontent.com/3473798/99278860-7cf1f780-2827-11eb-9f64-3bdbbe4751f1.png)

The human is surprised, despite bulldozer _technically_ doing exactly what it's told (zero required checks = vacuously true = mergey merge time)

**Comment by berler** [comment]
I'd also like to add that bulldozer instantly merging things can also cause confusion because the circle build may fail due to the branch being deleted before it even finishes checking it out. (I ran into this recently).

**Comment by bluekeyes** [comment]
I've added this to a list of bot issues we're hoping to fix in the next few weeks. One minor catch to @iamdanfox's example: while we can avoid merging when there are no required checks, people might then ask why Bulldozer _didn't_ merge the PR once all the checks passed. But that case is easier to explain and fix than having to revert something that might have been broken or unreviewed.

**Comment by berler** [comment]
Bulldozer could comment on a PR if it didn't merge just because there are no required checks, with instructions on how to override that so it is allowed, or point out where to go for admins to enable required checks (make it only comment max of once per PR this way).
