### ISSUE TITLE
github secrets read from kubernetes Secret object

### ISSUE THREAD

**Issue by ev1lm0nk3y** [palantir/bulldozer#126]
Hi there, I'm trying to build a helm chart from this project, but the `github.app` variables I don't want to set in a `values.yaml` file, no on the commandline. What would be really cool, is if there could be a way to read these required details from a k8s secret that contains everything you need.

It would be easy for me to mount the secrets appropriately in the pod, then the `github` section could have a `secrets_path`

**Comment by bluekeyes** [comment]
I'm not too familiar with how secrets are managed in k8s: is there a reason that having the secrets in a separate file is preferred to generating or storing the full configuration file with the secrets? If Bulldozer supported environment variables for secret values, would that also work or does it have to be a file?

**Comment by ev1lm0nk3y** [comment]
K8s secrets can be mounted as a filesystem object. So yeah, you could have the whole config as a secret that can be read, but how do you generate that config? I would have to script something. 

An environment variable would work perfectly in this situation. Read the contents of the secret into an environment variable and start the bulldozer container. That is a reasonable solution.

Otherwise, a flag that contains the location of secrets could be used too

**Comment by hkothari** [comment]
Any word on whether you plan to support an env variable? right now it's kind of a bummer having to store our secret in the file itself because it prevents us from storing our config in git

**Comment by bluekeyes** [comment]
Of the options discussed so far, I think using optional environment variables for secrets is what I prefer, so I'd like to support this, but I don't currently have an estimate for when it will be implemented.
