### ISSUE TITLE
Is there a guide to deploy bulldozer?

### ISSUE THREAD

**Issue by ashishb** [palantir/bulldozer#143]

**Comment by asvoboda** [comment]
Hey @ashishb,

We've (hopefully!) written down most of the relevant information in our [deplyoment readme](https://github.com/palantir/bulldozer#deployment). Let us know if you have any other questions or issues.

**Comment by ashishb** [comment]
@asvoboda Thanks. Posted a 404 issue I am facing at https://github.com/palantir/bulldozer/issues/144
