### ISSUE TITLE
Adding UPDATE ME after a pr is out of date does not update the pr

### ISSUE THREAD

**Issue by akarnani** [palantir/bulldozer#15]
Steps to reproduce:

1. Create a pr from foo -> master
2. Push a commit to master
3. Add the `UPDATE ME` label to your pr

Expected outcome: bulldozer updates the pr
Actual outcome: no action is taken

**Comment by bluekeyes** [comment]
This should be fixed as of 1.1.0; Bulldozer now responds to `pull_request` events which happen when labels are added.
