### ISSUE TITLE
"Update me" not working 

### ISSUE THREAD

**Issue by ashishb** [palantir/bulldozer#151]
Here's my bulldozer file: https://github.com/celo-org/celo-monorepo/blob/9517d642e8a3a2b8513f2eefeec83368a4537fe0/.bulldozer.yml

My "update me" label is `automerge` which is the same label for automerging PRs. Bulldozer did not update my PR but tried to merge it into master, which due to our branch protection settings failed. Is this a known issue?

```
{"level":"info","rid":"bl9kuujpt6pth9b9kdpg","github_event_type":"pull_request","github_delivery_id":"bde559b0-be26-11e9-92a4-ea57aa65a887","github_installation_id":1475537,"github_repository_owner":"celo-org","github_repository_name":"celo-monorepo","github_pr_num":441,"time":"2019-08-14T00:02:08.189375978Z","message":"Merge rejected due to unsatisfied condition: \"7 of 7 required status checks are expected.\""}
```

**Comment by ashishb** [comment]
Never mind. I just found out https://github.com/palantir/bulldozer/pull/137/

**Comment by bluekeyes** [comment]
Sorry for the confusion, we're also discussing changing this behavior in #145.
