### ISSUE TITLE
Webhook error when try to "The payload will be delivered to"

### ISSUE THREAD

**Issue by nanusefue** [palantir/bulldozer#161]
Hello,
I try to make a integrate  the project in my repo, but when try to configure the webhook i have this error.

Response 400
Body
**Invalid webhook headers or payload**
Thanks.

**Comment by bluekeyes** [comment]
Hi @nanusefue, it's a little hard to figure out what's happening based on the information you provided. Are you seeing that 400 error in the GitHub UI? Do you also have access to the Bulldozer server logs? If yes, can you share the logs for this request?

As a first guess at the problem, can you make sure the [`webhook_secret`](https://github.com/palantir/bulldozer/blob/develop/config/bulldozer.example.yml#L41) is the same value that is configured in the [GitHub App (Step 12)](https://developer.github.com/apps/building-github-apps/creating-a-github-app/)? Note that you should also never need to create a webhook manually; this is done automatically when you [install the app](https://developer.github.com/apps/installing-github-apps/#installing-your-private-github-app-on-your-repository).

**Comment by nanusefue** [comment]
Hi @bluekeyes sorry about my poor explication, I have this log from the server:

```
{"level":"warn","rid":"xxxxxx","github_event_type":"ping","github_delivery_id":"xxxxx-xxxx-xxxx-xxx-xxxxx","error":"payload signature check failed","time":"2019-11-16T14:53:28.057292778Z","message":"Received invalid webhook headers or payload"}

{"level":"info","rid":"xxxxxx","method":"POST","path":"/api/github/hook","status":400,"size":35,"elapsed":0.170404,"time":"2019-11-16T14:53:28.057349610Z","message":"http_request"}
```
I try to install the server in ecs aws using a fargate and alb to balance the server.
Thanks
Esteban
