### ISSUE TITLE
Add support for skipped checks

### ISSUE THREAD

**Issue by invliD** [palantir/bulldozer#164]
Right now bulldozer detects passed checks by comparing the sets of "required checks" and "successful checks", which is not entirely correct. Checks can also be in the state "skipped", in which case they should not count as failed, but they currently do.

**Comment by wrslatz** [comment]
I think support for `"neutral"` check run results should also be allowed. Ideally this would be configurable, as some users may want `"neutral"` checks to pass but `"skipped"` checks to fail. 

I can open a separate request for supporting `"netural"` check results, if you'd like.

#### Additional details

This only applies [checks](https://docs.github.com/en/rest/reference/checks#create-a-check-run--parameters) and not for [statuses](https://docs.github.com/en/rest/reference/repos#create-a-commit-status--parameters).

Checks:

Name | Type | In | Description
-- | -- | -- | --
conclusion | string | body | **Required if you provide `completed_at` or a `status` of `completed`.** The final conclusion of the check. Can be one of `action_required`, `cancelled`, `failure`, `neutral`, `success`, `skipped`, `stale`, or `timed_out`. When the conclusion is `action_required`, additional details should be provided on the site specified by `details_url`. </br>**Note:** Providing `conclusion` will automatically set the `status` parameter to `completed`. You cannot change a check run conclusion to `stale`, only GitHub can set this.

Statuses:

Name | Type | In | Description
-- | -- | -- | --
state | string | body | **Required.** The state of the status. Can be one of `error`, `failure`, `pending`, or `success`.

Relevant code section that would need to be changed:
https://github.com/palantir/bulldozer/blob/923a21ecad9dcd03e0d877bebcfeedeec45f9b34/pull/github_context.go#L233-L242

More info on checks and statuses: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks#types-of-status-checks-on-github

**Comment by wrslatz** [comment]
Also see https://github.community/t/does-a-neutral-check-run-conclusion-satisfy-a-required-check/13706

**Comment by wrslatz** [comment]
This blocks PRs from being auto-merged **even when Bulldozer isn't configured to require that specific check.**

In our example, we have a status check "Generic Check" that results in status `"neutral"`. Even though `Generic Check` is not included in `required_statuses`, I see the following in debug logs:

```
"message":"<org>/<repo>#<pr> is deemed not mergeable because of unfulfilled status checks: [Generic Check]"
```

#### Relevant code
Get required statuses from GitHub branch protections (i.e. not what's defined in bulldozer `required_statuses` config)
https://github.com/palantir/bulldozer/blob/923a21ecad9dcd03e0d877bebcfeedeec45f9b34/bulldozer/evaluate.go#L120
Evaluating required statuses
https://github.com/palantir/bulldozer/blob/923a21ecad9dcd03e0d877bebcfeedeec45f9b34/bulldozer/evaluate.go#L131-L140

**Comment by wrslatz** [comment]
Opened new issue for this https://github.com/palantir/bulldozer/issues/222

**Comment by bluekeyes** [comment]
As of #223, both "neutral" and "skipped" are considered valid conclusions for required checks (matching GitHub behavior) and will not block Bulldozer from merging the PR. This will be part of an upcoming release.

I think that fixes the issue reported here, but please let me know if I missed something and I'll reopen this.
