### ISSUE TITLE
Bulldozer Docker

### ISSUE THREAD

**Issue by fintecheando** [palantir/bulldozer#174]
I got this message when running docker using the lastest

bulldozer_1  | {"level":"info","rid":"bq0pgcuu2rntnt97v1tg","github_event_type":"pull_request","github_delivery_id":"dd5d0600-7251-11ea-9fae-3e7c9fb93e62","time":"2020-03-30T06:56:51.418501569Z","message":"Received webhook event"}
bulldozer_1  | {"level":"debug","rid":"bq0pgcuu2rntnt97v1tg","github_event_type":"pull_request","github_delivery_id":"dd5d0600-7251-11ea-9fae-3e7c9fb93e62","github_repository_owner":"InfotecMexico","github_repository_name":"bulldozer","github_pr_num":13,"method":"GET","path":"https://api.github.com/repos/InfotecMexico/bulldozer/pulls/13","status":-1,"size":-1,"elapsed":41.492391,"time":"2020-03-30T06:56:51.460627425Z","message":"github_request"}
bulldozer_1  | {"level":"error","rid":"bq0pgcuu2rntnt97v1tg","github_event_type":"pull_request","github_delivery_id":"dd5d0600-7251-11ea-9fae-3e7c9fb93e62","error":"failed to get pull request InfotecMexico/bulldozer#13: Get https://api.github.com/repos/InfotecMexico/bulldozer/pulls/13: could not refresh installation id 0's token: received non 2xx response status \"404 Not Found\" when fetching https://api.github.com/installations/0/access_tokens\ngithub.com/palantir/bulldozer/server/handler.(*PullRequest).Handle\n\t/go/src/github.com/palantir/bulldozer/server/handler/pull_request.go:61\ngithub.com/palantir/bulldozer/vendor/github.com/palantir/go-githubapp/githubapp.(*eventDispatcher).ServeHTTP\n\t/go/src/github.com/palantir/bulldozer/vendor/github.com/palantir/go-githubapp/githubapp/dispatcher.go:178\ngithub.com/palantir/bulldozer/vendor/goji%2eio.dispatch.ServeHTTP\n\t/go/src/github.com/palantir/bulldozer/vendor/goji.io/dispatch.go:17\ngithub.com/palantir/bulldozer/vendor/github.com/bluekeyes/hatpear.Recover.func1.1\n\t/go/src/github.com/palantir/bulldozer/vendor/github.com/bluekeyes/hatpear/hatpear.go:107\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/palantir/bulldozer/vendor/github.com/bluekeyes/hatpear.Catch.func1.1\n\t/go/src/github.com/palantir/bulldozer/vendor/github.com/bluekeyes/hatpear/hatpear.go:60\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/palantir/bulldozer/vendor/github.com/rs/zerolog/hlog.AccessHandler.func1.1\n\t/go/src/github.com/palantir/bulldozer/vendor/github.com/rs/zerolog/hlog/hlog.go:180\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/palantir/bulldozer/vendor/github.com/rs/zerolog/hlog.RequestIDHandler.func1.1\n\t/go/src/github.com/palantir/bulldozer/vendor/github.com/rs/zerolog/hlog/hlog.go:169\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/palantir/bulldozer/vendor/github.com/palantir/go-baseapp/baseapp.NewMetricsHandler.func1.1\n\t/go/src/github.com/palantir/bulldozer/vendor/github.com/palantir/go-baseapp/baseapp/middleware.go:55\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/palantir/bulldozer/vendor/github.com/rs/zerolog/hlog.NewHandler.func1.1\n\t/go/src/github.com/palantir/bulldozer/vendor/github.com/rs/zerolog/hlog/hlog.go:30\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/palantir/bulldozer/vendor/goji%2eio.(*Mux).ServeHTTP\n\t/go/src/github.com/palantir/bulldozer/vendor/goji.io/mux.go:74\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","time":"2020-03-30T06:56:51.460758467Z","message":"Unexpected error handling webhook request"}
bulldozer_1  | {"level":"info","rid":"bq0pgcuu2rntnt97v1tg","method":"POST","path":"/api/github/hook","status":500,"size":22,"elapsed":43.081676,"time":"2020-03-30T06:56:51.460787397Z","message":"http_request"}

**Comment by asvoboda** [comment]
It looks like your installation ID is set to 0, which is not correct. You'll want to follow the advice in https://github.com/palantir/bulldozer/issues/81#issuecomment-486603707

> The `integration_id` value in the config file must be `App id ` value of your app.
> You can find it on the `General` tab of your application (`Settings > Developer settings > GitHub Apps > {your app} > General `

**Comment by fintecheando** [comment]
Hi, thank you, I got fixed just clicking the "Create application" in GitHub
