### ISSUE TITLE
401 when attempting to merge

### ISSUE THREAD

**Issue by jmrossy** [palantir/bulldozer#177]
Hi,
I've set up a bulldozer instance v1.7.2 and configured bulldozer with the private key, integration_id, and webhook secret. 

I've configured the GitHub app with the permissions and checks listed in the README. 

<img width="774" alt="Screen Shot 2020-04-02 at 21 43 42" src="https://user-images.githubusercontent.com/710751/78315465-0ff55000-752b-11ea-8b5a-75046e3314c2.png">

In the bulldozer logs, I can see that Github is successfully posting to the instance and bulldozer is attempting to merge once the conditions have been met but it fails with a 401 error:

`"message":"Merge failed with unexpected status: 401: \"Bad credentials\""`

I've doubled checked for server time drift as mentioned in #158 but doesn't seem to be the case.

Any tips for how to debug from here?

**Comment by bluekeyes** [comment]
Sorry that you've run into this issue. From what you've described, it sounds like the configuration for the app in GitHub is correct.

For background, there are two authentication methods that are used. First, the private key is used to generate and sign a JWT. This token is used to get an OAuth token for a specific installation from GitHub. Bulldozer authenticates all other API requests using the OAuth token. While clock synchronization is important for creating the JWT, it does not matter once you have the OAuth token. Bulldozer should also automatically refresh the OAuth token when it expires after one hour.

You can test this process by hand using the guide here: https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app.

Some other things you can check are:

1. Is the application installed/enabled on the repository where the merge is happening?
2. Is the installation ID that Bulldozer is logging correct? You can see the installation ID in the settings for the organization that installed the app.
3. Did you set the [`push_restriction_user_token`](https://github.com/palantir/bulldozer/blob/develop/config/bulldozer.example.yml#L62) configuration option and does the repository have push restrictions enabled on the target branch? If yes to either of these, is the token in the configuration valid and does it have write permission on the repository?

If you can include additional logs for the failed merge, I might have other suggestions.

**Comment by jmrossy** [comment]
@bluekeyes thanks for the response! `push_restriction_user_token` was the missing piece here because of our branch protection rules. Closing issue :)

**Comment by bluekeyes** [comment]
Great! Note that in the latest versions of GitHub, you should be able to remove the `push_restriction_user_token` option completely from the configuration and instead set the `bulldozer` user as an allowed pusher in the branch protection settings. As a result, we'll probably remove the `push_restriction_user_token` option in a future release.
