### ISSUE TITLE
Open source excavator?

### ISSUE THREAD

**Issue by jared2501** [palantir/bulldozer#183]
Hey palantir infra team,

I'm not quite sure where else to put this so I thought i'd start here. Is there any chance of getting excavator open sourced? I used it during my time at palantir and thought it was suuuper helpful, I'd love to use it at my current company.

**Comment by bluekeyes** [comment]
Hey @jared2501, I'm glad you found Excavator useful while you were at Palantir. We'd like to release an open-source version but the code isn't in a state that's ready for outside use and I'm not sure when we'll have time to make the improvements we want to make. While I'm hopeful there will be a public release in the future, I don't have any estimate on when it will be.

Until then, and while it's not open-source, Sourcegraph is adding some Excavator-like functionality with their [code change management / campaigns](https://about.sourcegraph.com/product/code-change-management/) feature. I've only seen a demo and don't have any experience using it, but it could be worth checking out.

**Comment by jared2501** [comment]
Ah cool, thanks for the response & pointer @bluekeyes!

**Comment by sassafras-bypass** [comment]
@bluekeyes, Just following up here as I'm now another ex-Palantir employee who appreciated Excavator. Have there been any moves to open source it over the past 2 years?

**Comment by bluekeyes** [comment]
@sassafras-bypass  Unfortunately, no. While we've made improvements to Excavator internally, none of those have been working towards an open source release. It's still something I'd personally like to see happen but as before I don't know if or when that will be.
