### ISSUE TITLE
Add condition for draft PRs

### ISSUE THREAD

**Issue by radeklat** [palantir/bulldozer#191]
It would be useful to white/blacklist actions based on draft PR status. For example, to not auto-update PRs if they are in draft status as they clearly require more work.

**Comment by Yodablues** [comment]
Second this! Labels are nice, but being able to disable based on Draft would be great.

**Comment by bluekeyes** [comment]
Since draft PRs can't merge, this condition will only apply to updates. I'm tempted to simply ignore draft PRs completely instead of making the draft status a configuration option. Are there any practical cases where having Bulldozer update a draft PR is important?

**Comment by Yodablues** [comment]
From my perspective and for how I use Drafts, having Bulldozer not update a draft is perfectly fine. I use drafts as a way to get early feedback on a change, so I consider those as works in progress anyway.

**Comment by radeklat** [comment]
It would be fine for our purpose as well (we would have it always disabled). I suggested a flag for people who may want to use the update functionality on draft PRs. ~But I can't think of a reasonable use case myself.~

**Comment by radeklat** [comment]
I just found a use case for updating draft PRs - keeping a development branch up to date during busy development to prevent merge conflicts later. One could open a draft PR and bulldozer could keep merging in new commits as they appear. My team actually uses a tool that opens a draft PR as part of creating a new development branch.

**Comment by wrslatz** [comment]
Pulling the code path(s) that might need to be updated, if this were to be configurable. I may take on contributing this enhancement if I get time.

Code where PR is evaluated for whether it should be ignored for updating:
https://github.com/palantir/bulldozer/blob/42eee51fcd1bff85a1025ea16f8d41e8b0bdaf69/bulldozer/update.go#L34-L43

Which uses this to check if the PR is ignored:
https://github.com/palantir/bulldozer/blob/42eee51fcd1bff85a1025ea16f8d41e8b0bdaf69/bulldozer/evaluate.go#L27-L36

Which uses this to evaluate the pull request state and info against the passed config:
https://github.com/palantir/bulldozer/blob/42eee51fcd1bff85a1025ea16f8d41e8b0bdaf69/bulldozer/signals.go#L52-L130

I'm not sure if this would be a new, optional parameter under `UpdateConfig` (seems to make more sense than nested in the `Ignore` as a new `Signals` option)
https://github.com/palantir/bulldozer/blob/42eee51fcd1bff85a1025ea16f8d41e8b0bdaf69/bulldozer/config_v1.go#L67-L69

**Comment by wrslatz** [comment]
I'll have a PR up for configurable ignoring of updating draft PRs early this week 🤞🏻

**Comment by wrslatz** [comment]
PR is up! https://github.cloud.capitalone.com/comet/comet-actions/pull/684 🎉
