### ISSUE TITLE
Wildcard branch selection

### ISSUE THREAD

**Issue by andreyzher** [palantir/bulldozer#199]
Hi,

GitHub Branch protection policies can be setup with wildcards to protect several branches at once, e.g. `release/*`
Have you considered enabling the same for the `merge.trigger.branches` key in the configuration?

I have been running bulldozer 1.9.1 with a patch to enable wildcard behaviour without any issues, but I wonder if there is any appetite for this feature among the maintainers?

-Andrey

**Comment by asvoboda** [comment]
Hey @andreyzher,

I think this would make sense. We could add a new option for something like `branches_pattern` which is a list of regexes. Is this something you'd be willing to contribute?

**Comment by andreyzher** [comment]
Already had a version sitting on a fork - see what you think? Since GitHub policies don't distinguish between patterns and concrete branch names, I reused the same field already defined in the config spec.

If you would prefer to see it as a separate option (`branches_pattern`), I can refactor.
