### ISSUE TITLE
Run on public github repos

### ISSUE THREAD

**Issue by ash211** [palantir/bulldozer#20]
https://github.com/palantir/spark

I'd love to get the `MERGE WHEN READY` functionality on the public github repos I maintain, like palantir/spark above.

Is this something we could do?

**Comment by felixfbecker** [comment]
It would be so awesome to have bulldozer as a GitHub app that is free for open source repos

**Comment by bluekeyes** [comment]
I agree that this would be cool to offer, and we've had additional internal requests for it as well. We're currently in the process of rebuilding Bulldozer as a GitHub App (ETA is end of October or early November 2018) and will probably look into adding this for free to the GitHub Marketplace once the new version is finished.

**Comment by jmcampanini** [comment]
this is done. it's now running on the Palantir org

**Comment by deonna** [comment]
@jmcampanini -- Is the app currently discoverable on GitHub Marketplace? I can't seem to find it. If not, how would one install it?

**Comment by deepakmahakale** [comment]
> @jmcampanini -- Is the app currently discoverable on GitHub Marketplace? I can't seem to find it. If not, how would one install it?

1. You need to create a new GitHub app - https://github.com/organizations/< organization name >/settings/apps/new **or** https://github.com/settings/apps/new
2. Provide the webhook URL and webhook secret while creating the app 
3. Provide the required permissions and subscribe to events mentioned in [README.md](https://github.com/palantir/bulldozer/blob/develop/README.md#github-app-configuration)
4. Add the app id of the newly created app under **github.app.integration_id** 
    ![image](https://user-images.githubusercontent.com/14993828/59659273-80f99000-91c3-11e9-95b0-c18deeea593b.png)
5. Generate a private key for the app and add under **github.app.private_key**
![image](https://user-images.githubusercontent.com/14993828/59659343-a4243f80-91c3-11e9-9ca1-9c08abae1542.png)
6. Install that app to the organization

**Comment by asvoboda** [comment]
Hey @deonna,

Right now we don't offer Bulldozer as a public app on the marketplace. @deepakmahakale is correct in that you need to run your own instance of the bot. Sorry for the confusion here.

**Comment by EfstathiadisD** [comment]
Does this continue to be true? Do I need to run this service on my own infra, for both Public and Private Repos? I have a use case for both, and it would be perfect if I used a single solution. Thanks!

**Comment by bluekeyes** [comment]
Hi @EfstathiadisD, we still do not offer a hosted version of Bulldozer for use on GitHub.com (outside of the `palantir` organization.) You'll have to run your own instance of the service, but should be able to use it on both public and private repositories once you have it running.
