### ISSUE TITLE
Be able to use patterns for required_statuses

### ISSUE THREAD

**Issue by NargiT** [palantir/bulldozer#211]
Is it possible to use patterns for `required_statuses` to better integrate with `branch_patterns` ?

This would allow to drastically reduce the amount of `.bulldozer-bot.yaml` files and put most of the configuration in the `default_repository_config`

```
merge:
  required_statuses_patterns:
  - "policy-bot: .*"
  - "continous-integration/jenkins/pr-merge"
```

In order to keep minor version up to date with latest security patches (using renovate-bot) we would like to also auto-merge branch "release/x.y". But policy-bot creates a status with the branch name eg. `policy-bot: master`, `policy-bot: release/x.y` and this force us to create a new .bulldozer-bot.yaml for each minor release.

**Comment by NargiT** [comment]
Another solution would be to force policy-bot status name to be generic but this does not solve issues with other status checks outside of palantir scope.

**Comment by NargiT** [comment]
up ?

**Comment by asvoboda** [comment]
Another way to handle this problem is to set the status checks as required in the GH settings. Bulldozer (and anyone else) will be unable to merge the PR until the required status checks are fulfilled.

Would this approach work for your use-case?

**Comment by bluekeyes** [comment]
Also, using patterns for `required_statuses` makes it difficult to know when all possible statuses have arrived. For example, suppose my project has multiple CI jobs that post statuses like `ci/job1`, `ci/job2`, and so on. I want to require all of them, so I set the pattern `ci/.*` as required. But Bulldozer doesn't know how many matching status it should wait for before merging: should it merge after `ci/job2` or should it wait for a possible `ci/job3`?

One solution is to require only one matching status for each pattern, but this behavior could be confusing. While it would probably work for your case with Policy Bot (where you expect only a single status matching the pattern), it wouldn't work for the `ci/.*` case I outline and a person who tried it might be surprised when a PR merges earlier than expected.

**Comment by NargiT** [comment]
@asvoboda this works if branches are statics (master, dev, integration) which is not my case. We have branches per release, so need to keep them up to date with CVE patches.

@bluekeyes I would wait for all since it's a `.*` or use regex to filter the one I expect to be fullfield `ci/job[1-2]`. But I get the idea why you do not want to add it. Would that make sense then to add an option to policy instead, to allow a deterministic status name instead of one based on branch_names? e.g. `policy: $branch_name` -> `policy`

**Comment by bluekeyes** [comment]
Policy Bot actually has an undocumented server option for this that will post both a plain status and the status with the branch name:

```yaml
options:
  post_insecure_status_checks: true
```

The checks without the branch are insecure because it's easy to use a policy file on a different branch to generate a fake status and at least temporarily bypass the required check. You'll have to decide if the security tradeoff is worth the convenience of having a single check to require.

**Comment by NargiT** [comment]
not sure how another branch can affect the status of my branch.
because from what I know, a check_run is linked to a revision.

**Comment by NargiT** [comment]
https://github.com/palantir/policy-bot/blob/5250e2eb8f09364a1262e8503d05e67f19a194da/server/handler/base.go#L61-L64

I cannot really use it as it will be removed at some point 😢

**Comment by jamestoyer** [comment]
Hey @NargiT 

> not sure how another branch can affect the status of my branch.
> because from what I know, a check_run is linked to a revision.

So policy bot does not use check suites or check runs, and instead relies on the status APIs, although I believe you'll still get the same problem with check runs as, while they are tied to a commit, that commit can be on many PRs, so you'd need just one PR to pass and not all of them. That said, check suites and check runs also suck for forked repos right now too

**Comment by NargiT** [comment]
Ok so  tried to do what your were saying.

branches:
- master
- dev-branch
- feature-01 (rev 123)

Did a PR on dev-branch and master
![image](https://user-images.githubusercontent.com/3153333/97558669-b7ad0080-19dc-11eb-90cb-cb8e8d1fb8de.png)
So now I have 3 status per pull request, which is odd.

I ask one of my co worker to validate the pr concerning dev-branch and indeed the pr for master branch was also validated. :cry: 
![image](https://user-images.githubusercontent.com/3153333/97559131-55083480-19dd-11eb-95a6-a676f124255a.png)

So the solution proposed by @asvoboda make sens now. thanks
