### ISSUE TITLE
Avoid huge commit messages when squash-merging

### ISSUE THREAD

**Issue by bluekeyes** [palantir/bulldozer#22]
On one of our internal repositories, people submit changes from forks. These forks are sometimes out-of-date and are brought up-to-date by a series of merge commits. While GitHub correctly detects which files have changes, when Bulldozer squash-merges the PR, the resulting commit message can have hundreds of lines, including references to just about every commit that was included via one of the merges.

This makes history look pretty weird and can also lead to things like people getting mention emails from commits that merged months ago.

As a reviewer on the repo, it's unclear to me that this will happen before I add my approval, so it would be nice if Bulldozer could protect me from this result.

Some options:

1. Add a configuration option to always use the PR title and either an empty message body or the body of the PR.
2. Place some character limit on the size of the commit message; I don't know if GitHub exposes the generated message in the API
3. Use the same method as GitHub to generate commit messages (a list containing each member commit), but ignore all merge commits

**Comment by adidahiya** [comment]
+1, I would always use the empty message body option

**Comment by asvoboda** [comment]
This is now configurable with the 1.0 option set. Please let us know if anything isn't working as expected.
