### ISSUE TITLE
Allow additional, non-failing GitHub Checks' conclusions in statuses required for merging

### ISSUE THREAD

**Issue by wrslatz** [palantir/bulldozer#222]
#### Summary

Currently, `bulldozer` only allows Statuses and Checks ending in `success` to merge. This blocks users who have GitHub App(s) (or other tool implementing the Checks API) who report `neutral` or `skipped` `conclusion` when no action needs to be taken.

GitHub allows merging PRs with required [Checks](https://docs.github.com/en/rest/reference/checks) that complete with `conclusion` of `neutral` or `skipped`, in addition to `successful` (this is not explicitly documented but has been answered in support forums [here](https://github.community/t/does-a-neutral-check-run-conclusion-satisfy-a-required-check/13706/4) and [here](https://github.community/t/pr-stuck-waiting-for-checks-which-should-be-skipped/18485/3)).

For [Statuses](https://docs.github.com/en/rest/reference/repos#statuses), only those ending with `state ` of `success` allow for merging when required. No change is needed here.

#### Potential Solutions

1) Non-configurable support for additional Checks `conclusion`s
    - Add `"neutral"` and `"skipped"` Checks `conclusion`s to those considered as successful for merging
    - This would be a breaking change for existing users that want to require checks to only pass with `"success"` conclusion
    - The implementation for this would be simpler (no config needed)
1) Configurable support for additional Checks `conclusion`s
    - Add `allowed_check_conclusions` option to `merge` config, which takes multiple `conclusion` string value options that should be considered successful
    - Would not be a breaking change for existing users that want to require checks to only pass with `"success"` conclusion (default to `success` only if not provided)
    - More involved implementation
    - Might be more confusing for users to understand why `bulldozer` treats some Checks `conclusion`s differently than GitHub (would be simpler to just mirror GitHub functionality)

#### Additional Info

This only applies [checks](https://docs.github.com/en/rest/reference/checks#create-a-check-run--parameters) and not for [statuses](https://docs.github.com/en/rest/reference/repos#create-a-commit-status--parameters).

Checks:

Name | Type | In | Description
-- | -- | -- | --
conclusion | string | body | **Required if you provide `completed_at` or a `status` of `completed`.** The final conclusion of the check. Can be one of `action_required`, `cancelled`, `failure`, `neutral`, `success`, `skipped`, `stale`, or `timed_out`. When the conclusion is `action_required`, additional details should be provided on the site specified by `details_url`. </br>**Note:** Providing `conclusion` will automatically set the `status` parameter to `completed`. You cannot change a check run conclusion to `stale`, only GitHub can set this.

Statuses:

Name | Type | In | Description
-- | -- | -- | --
state | string | body | **Required.** The state of the status. Can be one of `error`, `failure`, `pending`, or `success`.

Relevant code section that would need to be changed:
https://github.com/palantir/bulldozer/blob/923a21ecad9dcd03e0d877bebcfeedeec45f9b34/pull/github_context.go#L233-L242

More info on checks and statuses: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks#types-of-status-checks-on-github

**Comment by bluekeyes** [comment]
Thanks for reporting this. Our internal usage of the Checks API mostly sticks to the success and failure conclusions, so we hadn't run into this issue yet. I think the solution will have two parts:

1. For checks that Bulldozer automatically waits for by inspecting the target branch protection, we should make sure Bulldozer matches GitHub's behavior. If GitHub will let you merge a PR with neutral and/or skipped required checks, then Bulldozer should do the same thing.

2. As you point out, this doesn't allow for customization around which conclusions (for which checks) are permissible. Adding new configuration options can fix this, but I'll have to think about exactly what should be configurable. My initial thought is to allow `required_status` to accept either the current list or a map from status name to list of allowed conclusions, where the default behavior if not specified matches the behavior for part (1)

**Comment by wrslatz** [comment]
> 1. For checks that Bulldozer automatically waits for by inspecting the target branch protection, we should make sure Bulldozer matches GitHub's behavior. If GitHub will let you merge a PR with neutral and/or skipped required checks, then Bulldozer should do the same thing.

I was hoping y'all would prefer this approach. It aligns with our intended usage as well and is simpler to implement. I'll work on a simple PR for this functionality to get some quick feedback.

> 2. ... My initial thought is to allow `required_status` to accept either the current list or a map from status name to list of allowed conclusions, where the default behavior if not specified matches the behavior for part (1)

I was thinking of adding a list of additional Check `conclusion`s that would be permissible across any Check results. Started with the name `allowed_check_conclusions`. This seemed simpler to implement and more aligned with current functionality (all results match against a specific value). I could look into implementing a per-status approach, though I worry it will get confusing configuring between Statuses (only one possible "success" outcome for merging) and Checks  (multiple "success" outcomes).

Would these two features need to be implemented together, or would completing `1.` by itself be acceptable?

**Comment by bluekeyes** [comment]
I think implementing the parts separately is fine, and I'm happy to review a PR for (1) if you'd like to make one. I view (1) as a bug to fix and (2) as an additional enhancement request that might be useful for some users.

**Comment by wrslatz** [comment]
I've made a fix and deployed and tested for some of our repos. Hoping to PR today or tomorrow.

**Comment by wrslatz** [comment]
PR is up 🚀
