### ISSUE TITLE
Bulldozer should work even when required status checks are disabled

### ISSUE THREAD

**Issue by adidahiya** [palantir/bulldozer#23]

**Comment by ryanmcnamara** [comment]
@adidahiya can you clarify?
Currently if you have no required status checks I believe bulldozer will immediately merge your pr, is this the behavior you're looking for?

**Comment by adidahiya** [comment]
Yes that's the behavior I'm looking for. It was not the case when I filed this issue, but I haven't tested it out since then.

**Comment by ryanmcnamara** [comment]
Yup I tested this out this morning on a new repo and that was the behavior
