### ISSUE TITLE
Push a new release?

### ISSUE THREAD

**Issue by f1sherman** [palantir/bulldozer#249]
Hello! Any chance you could push a new release now that https://github.com/palantir/bulldozer/pull/242 has been merged? Please let me know if there is another way I should request this!

**Comment by bluekeyes** [comment]
Sorry for the delay on this, I'll try to make a new release this week.

**Comment by f1sherman** [comment]
Thank you!

**Comment by bluekeyes** [comment]
https://github.com/palantir/bulldozer/releases/tag/v1.13.1
