### ISSUE TITLE
New trigger idea: auto_merge

### ISSUE THREAD

**Issue by heuels** [palantir/bulldozer#289]
Hello!

I recently noticed that GitHub started exposing pull request's `auto_merge` status. What do you think of adding support for that as a new trigger?

It would actually make a lot of sense in our use case – the main thing that we need from `bulldozer` is auto-updating pull requests when they've been marked as 'ready to merge'. However using native GitHub functionality to mark PRs as ready seems more natural than labels.

Happy to work on a PR!

**Comment by bluekeyes** [comment]
Adding the auto-merge status as a trigger condition sounds reasonable to me.

It looks like the `auto_merge` field is part of the v3 REST API, so it should be reasonably straightforward to add. While I don't think this is something we will implement, I'd be happy to review a PR if you or someone else would like to try implementing it.
