### ISSUE TITLE
BullDozer should allow ==MERGE_WHEN_READY== on comments, not just PR body

### ISSUE THREAD

**Issue by szunami** [palantir/bulldozer#31]
Seems like a much more natural fit to most GH PR workflows.

**Comment by tisba** [comment]
It would also be nice if BullDozer could watch for a user-defined "merge-when-ready" tag. I'd even prefer that over a comment.

**Comment by bluekeyes** [comment]
@tisba in `whitelist` mode, Bulldozer already respects certain standard labels for this; you can see the accepted text [here](https://github.com/palantir/bulldozer/blob/master/server/config/config.go#L37).

Does this satisfy your use case, or would you like to be able to customize this label text on a per-repository or per-server basis?

**Comment by bluekeyes** [comment]
Both custom labels and comments are supported in Bulldozer 1.0; see the updated configuration format in the README for more details.
