### ISSUE TITLE
Bulldozer cause the Jenkins build to trigger twice

### ISSUE THREAD

**Issue by ajayshrestha005** [palantir/bulldozer#315]
We build on each commit land to master. Commit land to master trigger the correct build in Jenkins. Bulldozer cause to trigger the build again which initiates the 2nd build. Not sure how it's happening

Any idea to fix this?

![Screen Shot 2022-05-26 at 6 08 00 PM](https://user-images.githubusercontent.com/45771560/170608505-ba35ef36-6fe1-4e1e-aaa3-058ccf7426e9.png)
![Screen Shot 2022-05-26 at 6 09 22 PM](https://user-images.githubusercontent.com/45771560/170608520-cd372074-8e63-4529-ac05-f6bf2c5d719b.png)

**Comment by bluekeyes** [comment]
Bulldozer merges PRs using the [Merge a pull request](https://docs.github.com/en/rest/pulls/pulls#merge-a-pull-request) API. This should be equivalent to clicking the "Merge" button in the UI for most purposes. I'm afraid I can't offer much more advice here without more details about the specific builds in Jenkins and how Jenkins triggers are configured.

For example, merging a pull request will generate both a `push` event for the `master` branch and a `closed` event for the pull request. Is it possible Jenkins is configured to run builds for both of these events?
