### ISSUE TITLE
Use PR title as squashed commit message

### ISSUE THREAD

**Issue by adidahiya** [palantir/bulldozer#32]
Somewhat related to #22 

I often update PR titles to be more accurate. When I do manual merges, I use that title in the merge, but when bulldozer squashes a 1-commit PR, it ends up using the original commit message of that commit in the squashed commit message.

**Comment by cobrabr** [comment]
I believe it does this even for PRs with more than 1 commit. It seems bulldozer picks that whatever the **original** PR title was as the default squash commit message.

**Comment by asvoboda** [comment]
This is now configurable with the 1.0 option set. Please let us know if anything isn't working as expected.
