### ISSUE TITLE
could not refresh installation id ####'s token: received non 2xx response status \"302 Found\" when fetching

### ISSUE THREAD

**Issue by ctm8788** [palantir/bulldozer#374]
Hi, 
I'm setting up Bulldozer on our Enterprise Github(3.5) .

I was running into the below issue and was unsure how to resolve.

Eventually, I fixed it by changing the below config.
Original: v3_api_url: "https://enterprise.company.com"

Fixed: v3_api_url: "https://enterprise.company.com/api/v3"

The Docs/example don't clearly specify what this should be.

Config: https://github.com/palantir/bulldozer/blob/c49fe9c94a9abf8e2a0f6805656f0822ce7654ba/config/bulldozer.example.yml#L48

Error Message:
`{"level":"error","rid":"cfhtohv068u0nnsr0ae0","github_event_type":"pull_request","github_delivery_id":"52fc9bc0-a7d6-11ed-8e89-b28edc883277","error":"failed to get pull request UserRepo/testbulldozer#6: Get \"https://enterprise.company.com/repos/UserRepo/testbulldozer/pulls/6\": could not refresh installation id 3093's token: received non 2xx response status \"302 Found\" when fetching https://enterprise.company.com/app/installations/3093/access_tokens\ngithub.com/palantir/bulldozer/server/handler.(*PullRequest).Handle\n\t/home/runner/work/bulldozer/bulldozer/server/handler/pull_request.go:62\ngithub.com/palantir/go-githubapp/githubapp.Dispatch.Execute\n\t/home/runner/work/bulldozer/bulldozer/vendor/github.com/palantir/go-githubapp/githubapp/scheduler.go:55\ngithub.com/palantir/go-githubapp/githubapp.(*scheduler).safeExecute\n\t/home/runner/work/bulldozer/bulldozer/vendor/github.com/palantir/go-githubapp/githubapp/scheduler.go:183\ngithub.com/palantir/go-githubapp/githubapp.QueueAsyncScheduler.func1\n\t/home/runner/work/bulldozer/bulldozer/vendor/github.com/palantir/go-githubapp/githubapp/scheduler.go:257\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/asm_amd64.s:1594","time":"2023-02-08T17:30:48.766268688Z","message":"Unexpected error handling webhook"}`

**Comment by ctm8788** [comment]
Using this Image: bulldozer:1.17.0

**Comment by bluekeyes** [comment]
Sorry this wasn't clear - I've updated the example config with a note about how to set this URL for GHES in #375.

**Comment by ctm8788** [comment]
Thanks!
