### ISSUE TITLE
Merge message should contain original PR title and body

### ISSUE THREAD

**Issue by iamdanfox** [palantir/bulldozer#39]
By default, when you merge a PR through the github UI, it helpfully copies the title into the commit message, that looks something like:

```
Merge pull request #XYZ from <branch>

<PR title>
```

Bulldozer actually drops the PR title and seems to push an empty commit body:

```
Merge pull request #XYZ from <branch>
```

## Proposal

It would make it easier to browse history using git-log if we could include a bit more information, e.g.:

```
#XYZ <PR Title>

<PR Description>
```

cc @alicederyn

**Comment by bluekeyes** [comment]
Some overlap with #22 and #32, in terms of customizing the merge messages. Right now, it looks like we [only set a message](https://github.com/palantir/bulldozer/blob/master/github/github.go#L313) if the merge method is "squash", which explains this behavior.

**Comment by coolnalu** [comment]
Yes it will be a good improvement!

**Comment by asvoboda** [comment]
This is now configurable with the 1.0 option set. Please let us know if anything isn't working as expected.
