### ISSUE TITLE
Don't Merge When Ready if a reviewer has Requested Changes

### ISSUE THREAD

**Issue by cmslewis** [palantir/bulldozer#42]
Say I have two reviews:
- 1 approval
- 1 request changes

If I have Merge When Ready on my PR, it Bulldozer will merge. Can we merge only if there are no Request Changes reviews in place?

**Comment by mkarp** [comment]
@cmslewis Have you tried making the target branch protected in the settings of the repository, and then also enabling the "Require pull request reviews before merging" setting? I think it does exactly what you want.

**Comment by asvoboda** [comment]
If there are required status checks that have not passed, GHE will not allow anyone to merge the PR (including Bulldozer).
