### ISSUE TITLE
+1 year without release :disappointed: 

### ISSUE THREAD

**Issue by NargiT** [palantir/bulldozer#471]
![image](https://github.com/palantir/bulldozer/assets/3153333/e52d9d2c-df35-43bd-834d-d90408763d28)

It's been 1 year without any release and there are a lot of new fix/commits since then. Could someone give us some internal status so we can decide if we wait or switch to another bot doing the equivalent.

Thanks in advance

**Comment by asvoboda** [comment]
It looks like the primary changes are just dependency upgrades: https://github.com/palantir/bulldozer/compare/v1.17.0...develop. Usually we don't cut a version unless there are specific features or fixes to get out. But I can chat with the team and we can create a new release.

**Comment by NargiT** [comment]
This feature is still in the develop branch : https://github.com/palantir/bulldozer/pull/370 and is very useful

**Comment by asvoboda** [comment]
https://github.com/palantir/bulldozer/releases/tag/v1.18.0

**Comment by NargiT** [comment]
Great thank you !
