### ISSUE TITLE
Question - blocking merging for other developers

### ISSUE THREAD

**Issue by oreporan** [palantir/bulldozer#49]
In order to allow bulldozer to merge, I can not check the `Restrict who can push to matching branches` in the `settings -> protected branch` 

How can I allow only bulldozer to merge PR's and not everyone with "write" permissions on the repo?

Is there any way to create some user called "bulldozer" and give these details to the bot?

**Comment by bluekeyes** [comment]
It looks like you may have figured this out, but the only currently supported way is to create a service/bot account, use that account to enable Bulldozer on repositories, and then restrict push permissions to only that account.

We're currently working to rebuild Bulldozer using GitHub App functionality. Once that is complete, you should be able to either only allow the application's user to push or allow no users to push and the bot will skip that check; I'm not quite sure yet how it will interact with branch protection.
