### ISSUE TITLE
Feature: fallback to global configuration when repo config file not found.

### ISSUE THREAD

**Issue by richard1122** [palantir/bulldozer#76]
Currently, we need to add a config file (eg .bulldozer.yml) to each repo.

I've add support for global configuration as repo fallback configuration. 

We can install bulldozer as GitHub app only to projects need to enable this feature.

You can view my implementation here: https://github.com/richard1122/bulldozer/commit/ee5a0b79d0855b83821cadec3eb5a73c31b05b36

If this feature is acceptable, I 'd like to send a PR.

**Comment by bluekeyes** [comment]
This sounds like a reasonable feature to add and I think your implementation is on the right track. I have a few comments on the details, but we can discuss that on the PR.
