### ISSUE TITLE
Bulldozer, on merge, should close issues that a PR resolves

### ISSUE THREAD

**Issue by mradamczyk** [palantir/bulldozer#78]
In the body of PR one can write `resolves #xyz`. Then normally, when manually closing a PR with merging, github closes the`xyz` issue. It would be super useful, if bulldozer do the same.

**Comment by bluekeyes** [comment]
Thanks for reporting this. I haven't confirmed yet, but I suspect this is an issue with the permissions we've granted Bulldozer on our internal installation. When a pull request is merged, the person who performs the merge is the person who closes the linked issue. My guess is that Bulldozer does not have permission to edit issue state, so GitHub silently skips this behavior.

**Comment by bluekeyes** [comment]
I've updated permissions for our internal installation and it seems to work now, but you may have to get an organization owner to accept the new permissions first.
