### ISSUE TITLE
Question: Would be open to have someone host this?

### ISSUE THREAD

**Issue by nambrot** [palantir/bulldozer#80]
Hey all,

thank you so much for making bulldozer. We recently were looking for options to our problems, and were surprised that there is no hosted option for something like bulldozer. Would you be OK with someone hosting bulldozer as a service?

**Comment by nambrot** [comment]
My understanding is that the Apache license allows for that, but I figure i ask

**Comment by ajlake** [comment]
Thanks for your interest in bulldozer. Please go right ahead! We were thinking about offering a hosted version for anyone to use for their github.com projects but aren't in any hurry to set it up (i.e. don't wait for us).

**Comment by nambrot** [comment]
Awesome, thank you for your support!
