### ISSUE TITLE
Document configuration and workflows

### ISSUE THREAD

**Issue by zombiezen** [palantir/bulldozer#82]
The README includes a sample configuration, but does not describe what the behavior of any of the settings are. (This prevented us on Go Cloud from considering Bulldozer for our project, see google/go-cloud#687.) Things in particular we'd like to understand are:

- Does this consider branch protections and code review approvals?
- Does this wait for CI to catch up?
- What happens if the original author adds more commits after the last review? Does that get merged in or does the bot stop?

**Comment by bluekeyes** [comment]
On review, I agree that the README doesn't clearly explain the behavior. Let me try to answer your questions here and then I'll update the README.

- Bulldozer can only merge a pull request when GitHub would allow a non-administrator with write access to merge it via the UI. This means that required statuses must pass and required reviews must be provided. You can also require additional status checks only for Bulldozer using the `required_statuses` key in the `merge` section (currently undocumented).
- Yes, Bulldozer will wait for CI builds to finish, provided that the CI builds post commit status when they complete and that these statuses are required via branch protection or the Bulldozer configuration.
- The behavior on new commits depends on how the rest of your project is configured. If your project is configured to dismiss reviews when new code is pushed, Bulldozer will wait for a new review before merging. However, if your project does not require new reviews when new code is pushed, Bulldozer will merge the pull request as soon as any required statuses pass on the new commits.

Whether this behavior applies to a given pull request or not is determined by the whitelist and blacklist settings. If a pull request matches the blacklist or does not match the whitelist, it is ignored completely.

**Comment by bluekeyes** [comment]
Looking at the linked issued, I'll also mention that Bulldozer can automate the "press update branch button" step using the `update` section of the configuration, which takes the same blacklist/whitelist configuration as the `merge` section.

**Comment by zombiezen** [comment]
Awesome, thanks for the info!
