### ISSUE TITLE
required_statuses pattern match

### ISSUE THREAD

**Issue by raviqqe** [palantir/bulldozer#88]
Hi. First, thanks for you all developers of this great tool.

I want pattern match for status checks which are defined in the `required_statuses` of `.bulldozer.yaml` because some CI status checks cannot be statically defined. For example, GitLab CI injects target branch names into their statuses (e.g. `ci/gitlab/<branch-name>`).

The solution will be a small change in `evaluate.go` where simple key existence check is used currently.

Can I hear your opinions?

**Comment by bluekeyes** [comment]
Thanks for your interest in Bulldozer! Can you provide a specific example of the workflow you want to support to make sure I understand the feature request? 

Our idea when designing `required_statuses` was that most statuses would be required via GitHub branch protection and that the Bulldozer configuration would only be needed if there were statuses that Bulldozer must wait for but that humans can ignore if needed.

**Comment by raviqqe** [comment]
It seems to be resolved by GitHub's branch protection. I'll check that tomorrow. Thanks!

**Comment by raviqqe** [comment]
The GitHub branch protection does not support any pattern matching for status check either but I realized that GitLab CI supports [static status names](https://docs.gitlab.com/ee/user/project/integrations/github.html). So I don't need pattern matching support by bulldozer itself for now. Thanks for your help!
