### ISSUE TITLE
Support status checks created by Checks API

### ISSUE THREAD

**Issue by renefritze** [palantir/bulldozer#96]
I've deployed bulldozer via the 1.4.0 tagged docker image and setup a GithubApp for our organization. I'm now trying out the config in a toy repository. In [this PR](https://github.com/pymor/ci_playground/pull/4) the first comment is matching the configured whitelisted "comment" and the second comment the "comment_substring". In the debug output however I see

> pymor_bulldozer_1  | 2019-03-07T08:03:17.357768662Z |DEBUG| pymor/ci_playground#4 is deemed not mergeable because of unfulfilled status checks: [pymor.ci_playground] 

Which seems wrong since that is the name of the only required status check and that passed.

**Comment by bluekeyes** [comment]
This does seems strange, but that message is expected for evaluations that take place before the status check is successful, for example when it is updated to indicate that tests are currently running.

Can you share more of the log output? Right now, my guess is that there is some other issue that is actually preventing the merge from happening.

**Comment by renefritze** [comment]
Can do. I've pushed a new commit to the dummy PR and got this:

> pymor_bulldozer_1  | 2019-03-08T08:55:31.936350404Z |INFO| Server listening on 0.0.0.0:8080
pymor_bulldozer_1  | 2019-03-08T08:55:52.472262654Z |INFO| Received webhook event github_delivery_id=f985ef9e-417f-11e9-8584-9d51ad0c5723 github_event_type=push rid=bi12s62glpuan12l8d40
pymor_bulldozer_1  | 2019-03-08T08:55:52.662358371Z |INFO| Received webhook event github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request rid=bi12s62glpuan12l8d4g
pymor_bulldozer_1  | 2019-03-08T08:55:53.374547577Z |DEBUG| github_request elapsed=897.15569 github_delivery_id=f985ef9e-417f-11e9-8584-9d51ad0c5723 github_event_type=push github_installation_id=725512 github_repository_name=ci_playground github_repository_owner=pymor method=GET path=https://api.github.com/repos/pymor/ci_playground/pulls?per_page=100&state=open rid=bi12s62glpuan12l8d40 size=-1 status=200
pymor_bulldozer_1  | 2019-03-08T08:55:53.375501014Z |DEBUG| found open pull request with base ref refs/heads/master github_delivery_id=f985ef9e-417f-11e9-8584-9d51ad0c5723 github_event_type=push github_installation_id=725512 github_repository_name=ci_playground github_repository_owner=pymor rid=bi12s62glpuan12l8d40
pymor_bulldozer_1  | 2019-03-08T08:55:53.375551330Z |DEBUG| received push event with base ref refs/heads/PR4 github_delivery_id=f985ef9e-417f-11e9-8584-9d51ad0c5723 github_event_type=push github_installation_id=725512 github_repository_name=ci_playground github_repository_owner=pymor rid=bi12s62glpuan12l8d40
pymor_bulldozer_1  | 2019-03-08T08:55:53.375604302Z |DEBUG| Doing nothing since push event affects no open pull requests github_delivery_id=f985ef9e-417f-11e9-8584-9d51ad0c5723 github_event_type=push github_installation_id=725512 github_repository_name=ci_playground github_repository_owner=pymor rid=bi12s62glpuan12l8d40
pymor_bulldozer_1  | 2019-03-08T08:55:53.375668531Z |INFO| http_request elapsed=1016.981851 method=POST path=/api/github/hook rid=bi12s62glpuan12l8d40 size=0 status=200
pymor_bulldozer_1  | 2019-03-08T08:55:53.745698692Z |DEBUG| github_request elapsed=1082.399726 github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request github_installation_id=725512 github_pr_num=4 github_repository_name=ci_playground github_repository_owner=pymor method=GET path=https://api.github.com/repos/pymor/ci_playground/pulls/4 rid=bi12s62glpuan12l8d4g size=-1 status=200
pymor_bulldozer_1  | 2019-03-08T08:55:53.746292578Z |DEBUG| Attempting to fetch configuration definition github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request github_installation_id=725512 github_pr_num=4 github_repository_name=ci_playground github_repository_owner=pymor path=.ci/bulldozer.yml ref=master rid=bi12s62glpuan12l8d4g
pymor_bulldozer_1  | 2019-03-08T08:55:53.977688080Z |DEBUG| github_request elapsed=191.401477 github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request github_installation_id=725512 github_pr_num=4 github_repository_name=ci_playground github_repository_owner=pymor method=GET path=https://api.github.com/repos/pymor/ci_playground/contents/.ci/bulldozer.yml?ref=master rid=bi12s62glpuan12l8d4g size=-1 status=200
pymor_bulldozer_1  | 2019-03-08T08:55:53.978265152Z |DEBUG| Bulldozer configuration is valid for "pymor/ci_playground ref=master" github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request github_installation_id=725512 github_pr_num=4 github_repository_name=ci_playground github_repository_owner=pymor rid=bi12s62glpuan12l8d4g
pymor_bulldozer_1  | 2019-03-08T08:55:54.131661204Z |DEBUG| github_request elapsed=153.273733 github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request github_installation_id=725512 github_pr_num=4 github_repository_name=ci_playground github_repository_owner=pymor method=GET path=https://api.github.com/repos/pymor/ci_playground/pulls/4/comments?per_page=100 rid=bi12s62glpuan12l8d4g size=2 status=200
pymor_bulldozer_1  | 2019-03-08T08:55:54.336038918Z |DEBUG| github_request elapsed=204.201249 github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request github_installation_id=725512 github_pr_num=4 github_repository_name=ci_playground github_repository_owner=pymor method=GET path=https://api.github.com/repos/pymor/ci_playground/issues/4/comments?per_page=100 rid=bi12s62glpuan12l8d4g size=-1 status=200
pymor_bulldozer_1  | 2019-03-08T08:55:54.336285925Z |DEBUG| pymor/ci_playground#4 is whitelisted because whitelisting is enabled and PR body matches one of specified whitelist comments: "BD: merge" github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request github_installation_id=725512 github_pr_num=4 github_repository_name=ci_playground github_repository_owner=pymor rid=bi12s62glpuan12l8d4g
pymor_bulldozer_1  | 2019-03-08T08:55:54.519175649Z |DEBUG| github_request elapsed=182.821732 github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request github_installation_id=725512 github_pr_num=4 github_repository_name=ci_playground github_repository_owner=pymor method=GET path=https://api.github.com/repos/pymor/ci_playground/branches/master/protection/required_status_checks rid=bi12s62glpuan12l8d4g size=-1 status=200
pymor_bulldozer_1  | 2019-03-08T08:55:54.709928268Z |DEBUG| github_request elapsed=187.029983 github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request github_installation_id=725512 github_pr_num=4 github_repository_name=ci_playground github_repository_owner=pymor method=GET path=https://api.github.com/repos/pymor/ci_playground/commits/6cf210b6a182b764f45c044055beece2c81efc53/status?per_page=100 rid=bi12s62glpuan12l8d4g size=-1 status=200
pymor_bulldozer_1  | 2019-03-08T08:55:54.710956727Z |DEBUG| pymor/ci_playground#4 is deemed not mergeable because of unfulfilled status checks: [pymor.ci_playground] github_delivery_id=f9c26730-417f-11e9-899c-718369fc1221 github_event_type=pull_request github_installation_id=725512 github_pr_num=4 github_repository_name=ci_playground github_repository_owner=pymor rid=bi12s62glpuan12l8d4g
pymor_bulldozer_1  | 2019-03-08T08:55:54.711189652Z |INFO| http_request elapsed=2048.909531 method=POST path=/api/github/hook rid=bi12s62glpuan12l8d4g size=0 status=200

And then I wanted to include the output from when the hook for the completed check fired, but that never happened. The Github app is subscribed to the 'Status' event, but that apparently does not trigger for the Azure check which is itself a GithubApp. I've now manually added a Webhook for that repository that triggers on "Check Run" and "Check suite", but I guess Bulldozer does not handle those: 

> pymor_bulldozer_1  | 2019-03-08T09:22:13.340010825Z |INFO| Received webhook event github_delivery_id=a80ce790-4183-11e9-8ff1-81da3167f10d github_event_type=check_suite rid=bi138haglpuan16jkugg
pymor_bulldozer_1  | 2019-03-08T09:22:13.340141713Z |INFO| http_request elapsed=0.244247 method=POST path=/api/github/hook rid=bi138haglpuan16jkugg size=0 status=202
pymor_bulldozer_1  | 2019-03-08T09:22:13.371051854Z |INFO| Received webhook event github_delivery_id=a8087ac0-4183-11e9-8a41-fa5fbb74c7f3 github_event_type=check_run rid=bi138haglpuan16jkuh0
pymor_bulldozer_1  | 2019-03-08T09:22:13.371123237Z |INFO| http_request elapsed=0.148625 method=POST path=/api/github/hook rid=bi138haglpuan16jkuh0 size=0 status=202
pymor_bulldozer_1  | 2019-03-08T09:22:20.449816941Z |INFO| Received webhook event github_delivery_id=ac551890-4183-11e9-90fc-61bb3ce23946 github_event_type=check_run rid=bi138j2glpuan16jkuhg
pymor_bulldozer_1  | 2019-03-08T09:22:20.449879061Z |INFO| http_request elapsed=0.125768 method=POST path=/api/github/hook rid=bi138j2glpuan16jkuhg size=0 status=202

**Comment by bluekeyes** [comment]
Ah, good catch! We don't have much experience with the Checks API yet (none of our internal tools use it), so I didn't realize that those events are reported differently. It's kind of confusing that they are rendered the same as traditional status checks in the UI.

I'm going to rename this issue to track adding support for the Checks API. I'm not sure when we'll have time to implement that, but PRs are welcome if you'd like to give it a shot.

**Comment by renefritze** [comment]
> PRs are welcome if you'd like to give it a shot.

I probably know just enough Go to tackle this if you can give me a pointer on how the tooling works. The Dockerfile just copies the already build app into the image and the Readme does not mention it AFAICT. How do I actually build the Go app?

**Comment by bluekeyes** [comment]
Ah, sorry about that - I'll update the README. You can compile the project by running `./godelw build` from the root directory and run all checks/tests by running `./godelw verify`. If you have Go installed on your system, you shouldn't need to install anything else.

For the changes themselves, I think you'll need to update the `CurrentSuccessStatuses` function: https://github.com/palantir/bulldozer/blob/develop/pull/github_context.go#L139. Hopefully it's possible to translate the Check API results into the existing status types, but if not, we could add a new method to `pull.Context` (something like `CurrentSuccessChecks`) and then also call that anywhere `CurrentSuccessStatuses` is called.

**Comment by renefritze** [comment]
`./godelw build` does not work for me:

> └───> ./godelw build
Downloading https://palantir.bintray.com/releases/com/palantir/godel/godel/2.10.0/godel-2.10.0.tgz to /home/rene/.godel/downloads/godel-2.10.0.tgz...
/home/rene/.godel/downloads/g 100%[===============================================>]  13,07M  17,6MB/s    in 0,7s    
Getting package from https://palantir.bintray.com/releases/com/palantir/distgo/dist-plugin/1.13.1/dist-plugin-1.13.1-linux-amd64.tgz...
 4.76 MiB / 4.76 MiB [====================================================================================] 100.00% 5s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-format-plugin/format-plugin/1.1.1/format-plugin-1.1.1-linux-amd64.tgz...
 3.32 MiB / 3.32 MiB [====================================================================================] 100.00% 2s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-format-asset-ptimports/ptimports-asset/1.1.0/ptimports-asset-1.1.0-linux-amd64.tgz...
 3.60 MiB / 3.60 MiB [====================================================================================] 100.00% 2s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-goland-plugin/goland-plugin/1.0.0/goland-plugin-1.0.0-linux-amd64.tgz...
 3.09 MiB / 3.09 MiB [====================================================================================] 100.00% 2s
Getting package from https://palantir.bintray.com/releases/com/palantir/okgo/check-plugin/1.1.1/check-plugin-1.1.1-linux-amd64.tgz...
 3.53 MiB / 3.53 MiB [====================================================================================] 100.00% 2s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-compiles/compiles-asset/1.1.1/compiles-asset-1.1.1-linux-amd64.tgz...
 5.29 MiB / 5.29 MiB [====================================================================================] 100.00% 3s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-deadcode/deadcode-asset/1.1.0/deadcode-asset-1.1.0-linux-amd64.tgz...
 5.32 MiB / 5.32 MiB [====================================================================================] 100.00% 4s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-errcheck/errcheck-asset/1.2.0/errcheck-asset-1.2.0-linux-amd64.tgz...
 5.45 MiB / 5.45 MiB [====================================================================================] 100.00% 6s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-extimport/extimport-asset/1.2.0/extimport-asset-1.2.0-linux-amd64.tgz...
 4.76 MiB / 4.76 MiB [====================================================================================] 100.00% 3s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-golint/golint-asset/1.1.0/golint-asset-1.1.0-linux-amd64.tgz...
 5.53 MiB / 5.53 MiB [====================================================================================] 100.00% 4s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-govet/govet-asset/1.1.0/govet-asset-1.1.0-linux-amd64.tgz...
 4.48 MiB / 4.48 MiB [====================================================================================] 100.00% 3s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-importalias/importalias-asset/1.1.0/importalias-asset-1.1.0-linux-amd64.tgz...
 4.78 MiB / 4.78 MiB [====================================================================================] 100.00% 3s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-ineffassign/ineffassign-asset/1.1.0/ineffassign-asset-1.1.0-linux-amd64.tgz...
 4.73 MiB / 4.73 MiB [====================================================================================] 100.00% 3s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-novendor/novendor-asset/1.1.0/novendor-asset-1.1.0-linux-amd64.tgz...
 4.84 MiB / 4.84 MiB [====================================================================================] 100.00% 3s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-outparamcheck/outparamcheck-asset/1.2.0/outparamcheck-asset-1.2.0-linux-amd64.tgz...
 5.48 MiB / 5.48 MiB [====================================================================================] 100.00% 3s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-unconvert/unconvert-asset/1.1.0/unconvert-asset-1.1.0-linux-amd64.tgz...
 5.56 MiB / 5.56 MiB [====================================================================================] 100.00% 4s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-okgo-asset-varcheck/varcheck-asset/1.1.0/varcheck-asset-1.1.0-linux-amd64.tgz...
 5.34 MiB / 5.34 MiB [====================================================================================] 100.00% 4s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-license-plugin/license-plugin/1.0.0/license-plugin-1.0.0-linux-amd64.tgz...
 3.30 MiB / 3.30 MiB [====================================================================================] 100.00% 3s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-test-plugin/test-plugin/1.0.0/test-plugin-1.0.0-linux-amd64.tgz...
 3.60 MiB / 3.60 MiB [====================================================================================] 100.00% 2s
Getting package from https://palantir.bintray.com/releases/com/palantir/godel-dep-plugin/dep-plugin/1.1.0/dep-plugin-1.1.0-linux-amd64.tgz...
 4.79 MiB / 4.79 MiB [====================================================================================] 100.00% 3s
Building bulldozer for linux-amd64 at build/bulldozer/1.4.0-1-g0d27463/linux-amd64/bulldozer
Error: go build failed: build command [go build -o /home/rene/projekte/uni/pymor/gitlab/bulldozer/build/bulldozer/1.4.0-1-g0d27463/linux-amd64/bulldozer -ldflags -X github.com/palantir/bulldozer/version.version=1.4.0-1-g0d27463 ./.] run in directory /home/rene/projekte/uni/pymor/gitlab/bulldozer with additional environment variables [GOOS=linux GOARCH=amd64 CGO_ENABLED=0] failed with output:

> ┐ (rene@bbeight) [08:23:20|Fr Mär 22] [develop] [~/projekte/uni/pymor/gitlab/bulldozer] 
└───> GOOS=linux GOARCH=amd64 CGO_ENABLED=0 !!
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 ./godelw build
Building bulldozer for linux-amd64 at build/bulldozer/1.4.0-1-g0d27463/linux-amd64/bulldozer
Error: go build failed: build command [go build -o /home/rene/projekte/uni/pymor/gitlab/bulldozer/build/bulldozer/1.4.0-1-g0d27463/linux-amd64/bulldozer -ldflags -X github.com/palantir/bulldozer/version.version=1.4.0-1-g0d27463 ./.] run in directory /home/rene/projekte/uni/pymor/gitlab/bulldozer with additional environment variables [GOOS=linux GOARCH=amd64 CGO_ENABLED=0] failed with output:

Either case provides no error message. I don't suppose you got a Docker image that has the right dev setup?

**Comment by bluekeyes** [comment]
I think you can use the container we use on CircleCI - this works for me locally:

```
docker run -it -v ${PWD}:/go/src/github.com/palantir/bulldozer -w /go/src/github.com/palantir/bulldozer nmiyake/go:go-darwin-linux-1.11-t134 ./godelw build
```

To avoid downloading Godel each time, you can mount the cache directory as well:

```
-v ~/.godel:/root/.godel
```

I imagine you could also `exec` into a persistent container or create a Docker volume, but I haven't tested that.

**Comment by renefritze** [comment]
I took your suggestion for a multi-stage build Dockerfile: https://gist.github.com/renefritze/f53bfa1a80d2ae470d72cce5ef3ae9c2

Which I drive from a minimal compose file
```yml
version: '2'
services:
  bulldozer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.compose
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ../secrets:/secrets
```


I can add that to #108 if wanted.

**Comment by bluekeyes** [comment]
I'd like to keep development improvements separate from changes to the code, but thank you for the example Dockerfile. I'll take a look at our full development process for Bulldozer and see how we can improve it.

**Comment by chdsbd** [comment]
I was playing around with bulldozer and just ran into this issue with [WIP](https://github.com/apps/wip), which uses the checks api.

I'm not sure if this has been considered this before, but from a cursory glance I think it may be more robust to check mergability by looking at the `mergable` key in the Github PR response.

PR doc: https://developer.github.com/v3/pulls/#response-1
More details on mergability: https://developer.github.com/v3/git/#checking-mergeability-of-pull-requests

__EDIT:__ After looking into this more it seems that checking the `mergable` key isn't sufficient to allow specifying required status checks.

**Comment by bluekeyes** [comment]
Yeah, as you discovered, the `mergable` property (which Bulldozer [does check](https://github.com/palantir/bulldozer/blob/develop/bulldozer/merge.go#L171)) indicates if there are merge conflicts (if a merge commit _can_ be created), and doesn't consider additional policies (if a merge commit _should_ be created.)

I believe the two things that need to be fixed in Bulldozer to support this are:

1. Responding to the check webhooks (in progress in #108) 
2. Listing check statuses in addition to traditional commit statuses. This is technically optional, but prevents Bulldozer from trying to merge too early and getting errors back from GitHub.

**Comment by kevinohara80** [comment]
Can confirm that this works on current snapshot
